* Frontend Development
** The basics
**** Definition
Front-end web development is the development of the graphical user interface of a website, through the use of HTML, CSS, and JavaScript, so that users can view and interact with that website.

**** Technologies
***** Fundamental
- HTML (HyperText Markup Language)
A markup language indicates text can be turned into images, tables, links, and other representations. It is the HTML code that provides an overall framework of how the site will look. HTML was developed by Tim Berners-Lee. The latest version of HTML is called HTML5 and was published on October 28, 2014 by the W3C recommendation.

- CSS (Cascading Style Sheets)
Cascading Style Sheets (CSS) controls the presentation aspect of the site and allows your site to have its own unique look. It does this by maintaining style sheets that sit on top of other style rules and are triggered based on other inputs, such as device screen size and resolution. The CSS can be added externally, internally, or embedded in the HTML tags.

- JavaScript
JavaScript is an event-based imperative programming language (as opposed to HTML's declarative language model) that is used to transform a static HTML page into a dynamic interface. JavaScript code can use the Document Object Model (DOM), provided by the HTML standard, to manipulate a web page in response to events, like user input.

***** Advanced stacks & tools
- Front-end frameworks are JavaScript libraries (with CSS and Bootstrap components) that assist you in creating a website, web app, or mobile app. Front End Frameworks make it much easier for developers to build the user interfaces of their web and mobile apps as web development evolves.
- A web content management system (WCM or WCMS) is a software content management system (CMS) specifically for web content.[1] It provides website authoring, collaboration, and administration tools that help users with little knowledge of web programming languages or markup languages create and manage website content.
